name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 4.0.0
homepage: https://github.com/tlserver/flutter_map_location_marker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_compass: ^0.7.0
  flutter_compass:
    path: ../flutter_compass
    # git: 
    #   url: https://github.com/thzero/flutter_compass
    #   ref: direction_issue
  flutter_map: ^1.1.1
  geolocator: ^9.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_joystick: ^0.0.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
